In [1]:
# analysis
import numpy as np
import pandas as pd 

# visualization
import matplotlib.pyplot as plt
import seaborn as sns

# single-cell
import scanpy as sc
import liana as li
import mudata as mu
import omnipath as op

from pathlib import Path
import os 

# seting global dir
cwd=Path.cwd()
if cwd.parent.parent.name == "resources":
    os.chdir(cwd.parent.parent.parent) 
print(os.getcwd())

# constants
PATH_DATA = Path('data/multimodal')
MOUSE_TAX_ID = 10090

/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
Downloading data from `https://omnipathdb.org/queries/enzsub?format=json`
Downloading data from `https://omnipathdb.org/queries/interactions?format=json`
Downloading data from `https://omnipathdb.org/queries/complexes?format=json`
Downloading data from `https://omnipathdb.org/queries/annotations?format=json`
Downloading data from `https://omnipathdb.org/queries/intercell?format=json`
Downloading data from `https://omnipathdb.org/about?format=text`

/home/maxi7524/repositories/project_computational_biology_initial_conditions_pymyboss

## Part 1 loading data

Loading part of

In [2]:
from OmniPhysiBoSS.io.mdata import run_mdata_processing_pipeline 
# ładujemy dane 
# create ann data objects
rna = sc.read(PATH_DATA / "sma_rna.h5ad") # 
msi = sc.read(PATH_DATA / "sma_msi.h5ad")
ct = sc.read(PATH_DATA / "sma_deconv.h5ad")

# create multimodal data
raw_mdata = mu.MuData({'rna':rna, 'ct':ct})
# raw_mdata = mu.MuData({'rna':rna, 'ct':ct})
print(raw_mdata)

mdata = run_mdata_processing_pipeline(raw_mdata, 'mouse')

MuData object with n_obs × n_vars = 3036 × 16534
  2 modalities
    rna:	3036 × 16486
      obs:	'in_tissue', 'array_row', 'array_col', 'x', 'y', 'lesion', 'region', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'n_genes', 'n_counts'
      var:	'gene_ids', 'feature_types', 'genome', 'mt', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'n_cells'
      uns:	'lesion_colors', 'log1p', 'region_colors', 'spatial'
      obsm:	'spatial'
      layers:	'counts'
    ct:	3036 × 48
      obs:	'in_tissue', 'array_row', 'array_col', 'x', 'y', 'lesion', 'region', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'n_genes', 'n_counts', 'uniform_density', 'rna_count_based_density'
      uns:	'lesion_colors', 'log1p', 'overlap_genes', 'region_colors', 'spatial', 'training_genes'
      obsm:	'spatial', 'tangram_ct_pred'
2026-06-13 19:47:43,787 | INFO     | OmniPhysiBoSS.io.mdata.mdata_pipeline:78 | Starting multi-modal processing pipeline orchestration.
2026-06-13 19:47:43,788 | INFO     | OmniPhysiBoSS.io.mdata.mdata_pipeline:105 | Initiating multimodal data intersection alignment across omics layers.
2026-06-13 19:47:43,788 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:34 | Starting multimodal data intersection alignment matrix pipeline.
2026-06-13 19:47:43,789 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:39 | --- MULTIMODAL DATA INTERSECTION ALIGNMENT & DATA LOSS REPORT ---
2026-06-13 19:47:43,790 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:52 | Modality Input Size - Layer 'rna': initially contains 3036 cells.
2026-06-13 19:47:43,791 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:52 | Modality Input Size - Layer 'ct': initially contains 3036 cells.
2026-06-13 19:47:43,792 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:71 | Data Retention Audit Trail:
2026-06-13 19:47:43,792 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:75 |  -> Modality 'rna': Retained 3036/3036 cells (100.00%). Lost 0 cells.
2026-06-13 19:47:43,793 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:75 |  -> Modality 'ct': Retained 3036/3036 cells (100.00%). Lost 0 cells.
2026-06-13 19:47:43,793 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:83 | Intersection Alignment Complete: 3036 cells mutually shared across all layers.
2026-06-13 19:47:43,942 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:114 | Linking main modality 'rna' tracking dictionaries directly to global root references.
2026-06-13 19:47:43,943 | INFO     | OmniPhysiBoSS.io.mdata.utils.common:34 | Initiating safe structural synchronization pipeline for MuData container.
2026-06-13 19:47:43,969 | INFO     | OmniPhysiBoSS.io.mdata.utils.common:67 | MuData structural state synchronization completed successfully.
2026-06-13 19:47:43,970 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:123 | Global structural array updates synchronized.
2026-06-13 19:47:43,970 | INFO     | OmniPhysiBoSS.io.mdata.mdata_pipeline:115 | Executing spatial neighborhood cross-correlation metrics using resource: mouseconsensus
2026-06-13 19:47:43,971 | INFO     | OmniPhysiBoSS.io.mdata.utils.spatial.liana_multimodal_pipeline:70 | Initializing run_liana_multimodal_pipeline execution tracking.
2026-06-13 19:47:43,972 | INFO     | OmniPhysiBoSS.io.mdata.utils.spatial.liana_multimodal_pipeline:79 | Scanning spatial density distributions for modality: 'rna'...
2026-06-13 19:47:44,225 | INFO     | OmniPhysiBoSS.io.mdata.utils.spatial.liana_multimodal_pipeline:91 | Optimal mathematical bandwidth isolated (k >= 6): 1724.1379310344828
2026-06-13 19:47:44,226 | INFO     | OmniPhysiBoSS.io.mdata.utils.spatial.liana_multimodal_pipeline:110 | Computing spatial neighbors into modality 'rna'.obsp['spatial_connectivities']...
2026-06-13 19:47:44,291 | INFO     | OmniPhysiBoSS.io.mdata.utils.common:34 | Initiating safe structural synchronization pipeline for MuData container.
2026-06-13 19:47:44,364 | INFO     | OmniPhysiBoSS.io.mdata.utils.common:67 | MuData structural state synchronization completed successfully.
2026-06-13 19:47:44,364 | INFO     | OmniPhysiBoSS.io.mdata.utils.spatial.liana_multimodal_pipeline:142 | Computing bivariate association scores via 'cosine'...

/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/legacy_api_wrap/__init__.py:88: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.

2026-06-13 19:49:37,070 | INFO     | OmniPhysiBoSS.io.mdata.utils.spatial.liana_multimodal_pipeline:154 | Local bivariate metrics successfully mapped to mdata['rna'].uns['liana_res']
2026-06-13 19:49:37,071 | INFO     | OmniPhysiBoSS.io.mdata.utils.common:34 | Initiating safe structural synchronization pipeline for MuData container.
2026-06-13 19:49:37,149 | INFO     | OmniPhysiBoSS.io.mdata.utils.common:67 | MuData structural state synchronization completed successfully.
2026-06-13 19:49:37,150 | INFO     | OmniPhysiBoSS.io.mdata.mdata_pipeline:126 | Fetching directed intracellular signaling graphs from OmniPath.
2026-06-13 19:49:37,151 | INFO     | OmniPhysiBoSS.io.mdata.utils.signalling_pathways.intracelluar_network:37 | Requesting intracellular pathways from OmniPath. Filtering via datasets: None, resources: None

Encountered invalid value(s) for `datasets`. Remaining values are `['collectri', 'dorothea', 'kinaseextra', 'ligrecextra', 'lncrna_mrna', 'mirnatarget', 'omnipath', 'pathwayextra', 'small_molecule', 'tf_mirna', 'tf_target']`

2026-06-13 19:49:41,034 | INFO     | OmniPhysiBoSS.io.mdata.utils.signalling_pathways.intracelluar_network:69 | Stored intracellular network under uns['intracellular_metadata_df']. Total edges: 172216
2026-06-13 19:49:41,046 | INFO     | OmniPhysiBoSS.io.mdata.mdata_pipeline:136 | Compiling intercellular metadata with OmniPath intercell annotations.
2026-06-13 19:49:41,049 | INFO     | OmniPhysiBoSS.io.mdata.utils.signalling_pathways.ligand_receptor_annotation:70 | Requesting comprehensive intercellular metadata network from OmniPath.
2026-06-13 19:49:56,330 | INFO     | OmniPhysiBoSS.io.mdata.utils.signalling_pathways.ligand_receptor_annotation:111 | Completed metadata attachment. Stored annotated dataframe under mdata.uns['intercellular_metadata_df'].
2026-06-13 19:49:56,350 | INFO     | OmniPhysiBoSS.io.mdata.mdata_pipeline:145 | Refreshing internal structural coordinates globally.
2026-06-13 19:49:56,351 | INFO     | OmniPhysiBoSS.io.mdata.utils.common:34 | Initiating safe structural synchronization pipeline for MuData container.
2026-06-13 19:49:56,423 | INFO     | OmniPhysiBoSS.io.mdata.utils.common:67 | MuData structural state synchronization completed successfully.
2026-06-13 19:49:56,424 | INFO     | OmniPhysiBoSS.io.mdata.mdata_pipeline:147 | Multi-modal processing pipeline completed successfully.

In [3]:
mdata

MuData object with n_obs × n_vars = 3036 × 16534
  uns:	'lesion_colors', 'log1p', 'region_colors', 'spatial', 'liana_res', 'intracellular_metadata_df', 'intercellular_metadata_df'
  obsm:	'spatial'
  obsp:	'spatial_connectivities'
  2 modalities
    rna:	3036 × 16486
      obs:	'in_tissue', 'array_row', 'array_col', 'x', 'y', 'lesion', 'region', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'n_genes', 'n_counts'
      var:	'gene_ids', 'feature_types', 'genome', 'mt', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'n_cells'
      uns:	'lesion_colors', 'log1p', 'region_colors', 'spatial', 'liana_res', 'intracellular_metadata_df', 'intercellular_metadata_df'
      obsm:	'spatial'
      layers:	'counts'
      obsp:	'spatial_connectivities'
    ct:	3036 × 48
      obs:	'in_tissue', 'array_row', 'array_col', 'x', 'y', 'lesion', 'region', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'n_genes', 'n_counts', 'uniform_density', 'rna_count_based_density'
      uns:	'lesion_colors', 'log1p', 'overlap_genes', 'region_colors', 'spatial', 'training_genes'
      obsm:	'spatial', 'tangram_ct_pred'

In [4]:
mdata.uns['intracellular_metadata_df']

        source                        target  sign
0       P49683                        P50148     1
1       P08631                        Q9UHD2    -1
2       Q02156                        Q86XR7     1
3       Q86X55                        P23759     1
4       P05771                        P11388     1
...        ...                           ...   ...
172211  O15084                        P36873     1
172212  Q09013                        P11831     1
172213  O95996  COMPLEX:O15169_P25054_P49841     1
172214  P31751                        P49815    -1
172215  Q15418                        Q05195    -1

[172216 rows x 3 columns]

In [5]:
mdata.uns['intercellular_metadata_df']

,interaction,ligand,receptor,ligand_means,ligand_props,receptor_means,receptor_props,morans,morans_pvals,mean,...,category_source_intercell_target,uniprot_intercell_target,genesymbol_intercell_target,entity_type_intercell_target,consensus_score_intercell_target,transmitter_intercell_target,receiver_intercell_target,secreted_intercell_target,plasma_membrane_transmembrane_intercell_target,plasma_membrane_peripheral_intercell_target
0,Adam10^Tspan15,Adam10,Tspan15,0.263227,0.232543,0.077425,0.059618,0.007305,0.000,0.107819,...,resource_specific,O95858,TSPAN15,protein,4.0,False,True,False,True,False
1,Adam10^Tspan12,Adam10,Tspan12,0.263227,0.232543,0.080002,0.075099,0.004899,0.008,0.126249,...,resource_specific,O95859,TSPAN12,protein,2.0,False,True,False,True,False
2,Adam10^Axl,Adam10,Axl,0.263227,0.232543,0.139795,0.129776,0.008614,0.000,0.188314,...,resource_specific,P30530,AXL,protein,22.0,False,True,False,True,False
3,Adam10^Notch1,Adam10,Notch1,0.263227,0.232543,0.059135,0.053360,0.006963,0.000,0.112873,...,resource_specific,P46531,NOTCH1,protein,22.0,False,True,False,True,False
4,Adam10^Nrcam,Adam10,Nrcam,0.263227,0.232543,0.581581,0.448617,0.011226,0.000,0.329722,...,resource_specific,Q92823,NRCAM,protein,9.0,False,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404,Mfge8^Itgb5,Mfge8,Itgb5,1.321266,0.743412,0.184464,0.157444,0.012872,0.000,0.339254,...,resource_specific,P18084,ITGB5,protein,14.0,False,True,False,True,False
405,Ado^Adora2a,Ado,Adora2a,0.209846,0.176219,0.391031,0.271080,-0.007733,1.000,0.176485,...,resource_specific,P29274,ADORA2A,protein,10.0,False,True,False,True,False
406,Gdf11^Actr2,Gdf11,Actr2,0.069398,0.063241,0.411245,0.342885,0.003359,0.063,0.131531,...,NaN,None,None,NaN,NaN,None,None,None,None,None
407,Inhba^Actr2,Inhba,Actr2,0.075964,0.070817,0.411245,0.342885,0.001451,0.252,0.151661,...,NaN,None,None,NaN,NaN,None,None,None,None,None
408,C4b^Nrp1,C4b,Nrp1,0.102229,0.083004,0.157399,0.135705,-0.000346,0.548,0.083255,...,NaN,None,None,NaN,NaN,None,None,None,None,None

## Part 2 models module

### Cells classes

In [7]:
mdata.mod['rna'].obs

,in_tissue,array_row,array_col,x,y,lesion,region,n_genes_by_counts,log1p_n_genes_by_counts,total_counts,log1p_total_counts,pct_counts_in_top_50_genes,pct_counts_in_top_100_genes,pct_counts_in_top_200_genes,pct_counts_in_top_500_genes,total_counts_mt,log1p_total_counts_mt,pct_counts_mt,n_genes,n_counts
GAATTTCTCGCTGCAG-1,1,28,30,13893,19495,intact,striatum,1520,7.327123,3036.0,8.018625,33.992095,40.513834,49.472991,66.403162,878.0,6.778785,28.919632,1520,3036.0
GCTCCGCTCGCTTCAG-1,1,42,112,37650,26623,lesioned,not_striatum,976,6.884487,1479.0,7.299798,25.287356,34.550372,47.532116,67.816092,274.0,5.616771,18.526031,976,1479.0
CCAAGCGTAACTCGTA-1,1,33,71,25774,22050,lesioned,not_striatum,1260,7.139660,2661.0,7.886833,34.047351,43.818113,54.904171,71.439309,446.0,6.102559,16.760616,1260,2661.0
TAACTATTACGCCAAA-1,1,29,107,36218,20060,lesioned,not_striatum,2943,7.987524,7424.0,8.912608,30.549569,36.341595,44.073276,58.445582,2081.0,7.641084,28.030712,2943,7424.0
CTATAAGAGCCAATCG-1,1,26,100,34193,18541,lesioned,not_striatum,2889,7.969012,7544.0,8.928640,31.216861,37.128844,45.320785,59.915164,1995.0,7.598900,26.444859,2889,7544.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCCTCTACGAGATGGC-1,1,26,32,14476,18488,intact,striatum,1428,7.264730,3312.0,8.105609,43.810386,50.181159,57.789855,71.980676,1214.0,7.102499,36.654587,1428,3312.0
GCACTGTGCAAATGTA-1,1,9,33,14789,9911,intact,not_striatum,1912,7.556428,3965.0,8.285513,30.088272,36.620429,45.346784,62.345523,1056.0,6.963190,26.633039,1912,3965.0
TACCTTAAGATTTCCC-1,1,49,29,13574,30089,intact,striatum,3484,8.156223,10977.0,9.303649,36.366949,41.878473,49.111779,62.175458,3810.0,8.245646,34.708939,3484,10977.0
AATGATGATACGCTAT-1,1,23,93,32167,17022,lesioned,not_striatum,2246,7.717351,5579.0,8.626944,36.099659,42.032622,49.901416,64.097509,1644.0,7.405496,29.467646,2246,5579.0
ATACCACGGGCAACTT-1,1,35,29,13594,23026,intact,striatum,2717,7.907652,8195.0,9.011401,42.953020,48.297743,55.253203,67.467968,3257.0,8.088869,39.743744,2717,8195.0