In [1]:
# analysis
import numpy as np
import pandas as pd 

# visualization
import matplotlib.pyplot as plt
import seaborn as sns

# single-cell
import scanpy as sc
import liana as li
import mudata as mu
import omnipath as op

from pathlib import Path
import os 

# seting global dir
cwd=Path.cwd()
if cwd.parent.parent.name == "resources":
    os.chdir(cwd.parent.parent.parent) 
print(os.getcwd())

# constants
PATH_DATA = Path('data/multimodal')
MOUSE_TAX_ID = 10090

/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
Downloading data from `https://omnipathdb.org/queries/enzsub?format=json`
Downloading data from `https://omnipathdb.org/queries/interactions?format=json`
Downloading data from `https://omnipathdb.org/queries/complexes?format=json`
Downloading data from `https://omnipathdb.org/queries/annotations?format=json`
Downloading data from `https://omnipathdb.org/queries/intercell?format=json`
Downloading data from `https://omnipathdb.org/about?format=text`
Failed to download from `https://omnipathdb.org/`.
Traceback (most recent call last):
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/urllib3/connection.py", line 204, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1106, in _validate_conn
    conn.connect()
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/urllib3/connection.py", line 759, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<HTTPSConnection(host='omnipathdb.org', port=443) at 0x7199f96cdac0>, 'Connection to omnipathdb.org timed out. (connect timeout=1.0)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/requests/adapters.py", line 696, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/urllib3/connectionpool.py", line 842, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/urllib3/util/retry.py", line 543, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='omnipathdb.org', port=443): Max retries exceeded with url: /about?format=text (Caused by ConnectTimeoutError(<HTTPSConnection(host='omnipathdb.org', port=443) at 0x7199f96cdac0>, 'Connection to omnipathdb.org timed out. (connect timeout=1.0)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/omnipath/_core/downloader/_downloader.py", line 143, in maybe_download
    res = self._download(req)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/omnipath/_core/downloader/_downloader.py", line 182, in _download
    with self._session.send(req, **settings) as resp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/requests/sessions.py", line 784, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/requests/adapters.py", line 717, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='omnipathdb.org', port=443): Max retries exceeded with url: /about?format=text (Caused by ConnectTimeoutError(<HTTPSConnection(host='omnipathdb.org', port=443) at 0x7199f96cdac0>, 'Connection to omnipathdb.org timed out. (connect timeout=1.0)'))

Downloading data from `http://no-tls.omnipathdb.org/about?format=text`
Failed to download from `http://no-tls.omnipathdb.org/`.
Traceback (most recent call last):
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/omnipath/_core/downloader/_downloader.py", line 143, in maybe_download
    res = self._download(req)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/omnipath/_core/downloader/_downloader.py", line 183, in _download
    resp.raise_for_status()
  File "/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/requests/models.py", line 1167, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://no-tls.omnipathdb.org/about?format=text

/home/maxi7524/repositories/project_computational_biology_initial_conditions_pymyboss

In [2]:
from OmniPhysiBoSS.io.mdata import run_mdata_processing_pipeline 
# ładujemy dane 
# create ann data objects
rna = sc.read(PATH_DATA / "sma_rna.h5ad") # 
msi = sc.read(PATH_DATA / "sma_msi.h5ad")
ct = sc.read(PATH_DATA / "sma_deconv.h5ad")

# create multimodal data
raw_mdata = mu.MuData({'rna':rna, 'ct':ct})
# raw_mdata = mu.MuData({'rna':rna, 'ct':ct})
print(raw_mdata)

mdata = run_mdata_processing_pipeline(raw_mdata, 'mouse')

MuData object with n_obs × n_vars = 3036 × 16534
  2 modalities
    rna:	3036 × 16486
      obs:	'in_tissue', 'array_row', 'array_col', 'x', 'y', 'lesion', 'region', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'n_genes', 'n_counts'
      var:	'gene_ids', 'feature_types', 'genome', 'mt', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'n_cells'
      uns:	'lesion_colors', 'log1p', 'region_colors', 'spatial'
      obsm:	'spatial'
      layers:	'counts'
    ct:	3036 × 48
      obs:	'in_tissue', 'array_row', 'array_col', 'x', 'y', 'lesion', 'region', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'n_genes', 'n_counts', 'uniform_density', 'rna_count_based_density'
      uns:	'lesion_colors', 'log1p', 'overlap_genes', 'region_colors', 'spatial', 'training_genes'
      obsm:	'spatial', 'tangram_ct_pred'
2026-06-13 10:08:27,502 | INFO     | OmniPhysiBoSS.io.mdata.mdata_pipeline:78 | Starting multi-modal processing pipeline orchestration.
2026-06-13 10:08:27,502 | INFO     | OmniPhysiBoSS.io.mdata.mdata_pipeline:105 | Initiating multimodal data intersection alignment across omics layers.
2026-06-13 10:08:27,503 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:34 | Starting multimodal data intersection alignment matrix pipeline.
2026-06-13 10:08:27,503 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:39 | --- MULTIMODAL DATA INTERSECTION ALIGNMENT & DATA LOSS REPORT ---
2026-06-13 10:08:27,504 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:52 | Modality Input Size - Layer 'rna': initially contains 3036 cells.
2026-06-13 10:08:27,505 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:52 | Modality Input Size - Layer 'ct': initially contains 3036 cells.
2026-06-13 10:08:27,507 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:71 | Data Retention Audit Trail:
2026-06-13 10:08:27,508 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:75 |  -> Modality 'rna': Retained 3036/3036 cells (100.00%). Lost 0 cells.
2026-06-13 10:08:27,510 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:75 |  -> Modality 'ct': Retained 3036/3036 cells (100.00%). Lost 0 cells.
2026-06-13 10:08:27,510 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:83 | Intersection Alignment Complete: 3036 cells mutually shared across all layers.
2026-06-13 10:08:27,655 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:114 | Linking main modality 'rna' tracking dictionaries directly to global root references.
2026-06-13 10:08:27,657 | INFO     | OmniPhysiBoSS.io.mdata.utils.common:34 | Initiating safe structural synchronization pipeline for MuData container.
2026-06-13 10:08:27,682 | INFO     | OmniPhysiBoSS.io.mdata.utils.common:67 | MuData structural state synchronization completed successfully.
2026-06-13 10:08:27,682 | INFO     | OmniPhysiBoSS.io.mdata.utils.unify.unify_modalities:123 | Global structural array updates synchronized.
2026-06-13 10:08:27,683 | INFO     | OmniPhysiBoSS.io.mdata.mdata_pipeline:115 | Executing spatial neighborhood cross-correlation metrics using resource: mouseconsensus
2026-06-13 10:08:27,684 | INFO     | OmniPhysiBoSS.io.mdata.utils.spatial.liana_multimodal_pipeline:70 | Initializing run_liana_multimodal_pipeline execution tracking.
2026-06-13 10:08:27,684 | INFO     | OmniPhysiBoSS.io.mdata.utils.spatial.liana_multimodal_pipeline:79 | Scanning spatial density distributions for modality: 'rna'...
2026-06-13 10:08:27,941 | INFO     | OmniPhysiBoSS.io.mdata.utils.spatial.liana_multimodal_pipeline:91 | Optimal mathematical bandwidth isolated (k >= 6): 1724.1379310344828
2026-06-13 10:08:27,942 | INFO     | OmniPhysiBoSS.io.mdata.utils.spatial.liana_multimodal_pipeline:110 | Computing spatial neighbors into modality 'rna'.obsp['spatial_connectivities']...
2026-06-13 10:08:28,002 | INFO     | OmniPhysiBoSS.io.mdata.utils.common:34 | Initiating safe structural synchronization pipeline for MuData container.
2026-06-13 10:08:28,079 | INFO     | OmniPhysiBoSS.io.mdata.utils.common:67 | MuData structural state synchronization completed successfully.
2026-06-13 10:08:28,080 | INFO     | OmniPhysiBoSS.io.mdata.utils.spatial.liana_multimodal_pipeline:142 | Computing bivariate association scores via 'cosine'...

/home/maxi7524/micromamba/envs/OmniPhysiBoss_env/lib/python3.12/site-packages/legacy_api_wrap/__init__.py:88: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.

2026-06-13 10:10:26,995 | INFO     | OmniPhysiBoSS.io.mdata.utils.spatial.liana_multimodal_pipeline:154 | Local bivariate metrics successfully mapped to mdata['rna'].uns['liana_res']
2026-06-13 10:10:26,996 | INFO     | OmniPhysiBoSS.io.mdata.utils.common:34 | Initiating safe structural synchronization pipeline for MuData container.
2026-06-13 10:10:27,067 | INFO     | OmniPhysiBoSS.io.mdata.utils.common:67 | MuData structural state synchronization completed successfully.
2026-06-13 10:10:27,068 | INFO     | OmniPhysiBoSS.io.mdata.mdata_pipeline:126 | Fetching directed intracellular signaling graphs from OmniPath.
2026-06-13 10:10:27,068 | INFO     | OmniPhysiBoSS.io.mdata.utils.signalling_pathways.intracelluar_network:37 | Requesting intracellular pathways from OmniPath. Filtering via datasets: None, resources: None

Encountered invalid value(s) for `datasets`. Remaining values are `['collectri', 'dorothea', 'kinaseextra', 'ligrecextra', 'lncrna_mrna', 'mirnatarget', 'omnipath', 'pathwayextra', 'small_molecule', 'tf_mirna', 'tf_target']`

2026-06-13 10:10:31,073 | INFO     | OmniPhysiBoSS.io.mdata.utils.signalling_pathways.intracelluar_network:69 | Stored intracellular network under uns['intracellular_metadata_df']. Total edges: 172216
2026-06-13 10:10:31,089 | INFO     | OmniPhysiBoSS.io.mdata.mdata_pipeline:136 | Compiling intercellular metadata with OmniPath intercell annotations.
2026-06-13 10:10:31,092 | INFO     | OmniPhysiBoSS.io.mdata.utils.signalling_pathways.ligand_receptor_annotation:70 | Requesting comprehensive intercellular metadata network from OmniPath.
2026-06-13 10:10:47,562 | INFO     | OmniPhysiBoSS.io.mdata.utils.signalling_pathways.ligand_receptor_annotation:111 | Completed metadata attachment. Stored annotated dataframe under mdata.uns['intercellular_metadata_df'].
2026-06-13 10:10:47,582 | INFO     | OmniPhysiBoSS.io.mdata.mdata_pipeline:145 | Refreshing internal structural coordinates globally.
2026-06-13 10:10:47,583 | INFO     | OmniPhysiBoSS.io.mdata.utils.common:34 | Initiating safe structural synchronization pipeline for MuData container.
2026-06-13 10:10:47,657 | INFO     | OmniPhysiBoSS.io.mdata.utils.common:67 | MuData structural state synchronization completed successfully.
2026-06-13 10:10:47,658 | INFO     | OmniPhysiBoSS.io.mdata.mdata_pipeline:147 | Multi-modal processing pipeline completed successfully.

In [8]:
mdata

MuData object with n_obs × n_vars = 3036 × 16534
  uns:	'lesion_colors', 'log1p', 'region_colors', 'spatial', 'liana_res', 'intracellular_metadata_df', 'intercellular_metadata_df'
  obsm:	'spatial'
  obsp:	'spatial_connectivities'
  2 modalities
    rna:	3036 × 16486
      obs:	'in_tissue', 'array_row', 'array_col', 'x', 'y', 'lesion', 'region', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'n_genes', 'n_counts'
      var:	'gene_ids', 'feature_types', 'genome', 'mt', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'n_cells'
      uns:	'lesion_colors', 'log1p', 'region_colors', 'spatial', 'liana_res', 'intracellular_metadata_df', 'intercellular_metadata_df'
      obsm:	'spatial'
      layers:	'counts'
      obsp:	'spatial_connectivities'
    ct:	3036 × 48
      obs:	'in_tissue', 'array_row', 'array_col', 'x', 'y', 'lesion', 'region', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'n_genes', 'n_counts', 'uniform_density', 'rna_count_based_density'
      uns:	'lesion_colors', 'log1p', 'overlap_genes', 'region_colors', 'spatial', 'training_genes'
      obsm:	'spatial', 'tangram_ct_pred'

In [7]:
mdata.uns['intracellular_metadata_df']

        source                        target  sign
0       P49683                        P50148     1
1       P08631                        Q9UHD2    -1
2       Q02156                        Q86XR7     1
3       Q86X55                        P23759     1
4       P05771                        P11388     1
...        ...                           ...   ...
172211  O15084                        P36873     1
172212  Q09013                        P11831     1
172213  O95996  COMPLEX:O15169_P25054_P49841     1
172214  P31751                        P49815    -1
172215  Q15418                        Q05195    -1

[172216 rows x 3 columns]

In [9]:
mdata.uns['intercellular_metadata_df']

,interaction,ligand,receptor,ligand_means,ligand_props,receptor_means,receptor_props,morans,morans_pvals,mean,...,category_source_intercell_target,uniprot_intercell_target,genesymbol_intercell_target,entity_type_intercell_target,consensus_score_intercell_target,transmitter_intercell_target,receiver_intercell_target,secreted_intercell_target,plasma_membrane_transmembrane_intercell_target,plasma_membrane_peripheral_intercell_target
0,Adam10^Tspan15,Adam10,Tspan15,0.263227,0.232543,0.077425,0.059618,0.007310,0.000,0.107815,...,resource_specific,O95858,TSPAN15,protein,4.0,False,True,False,True,False
1,Adam10^Tspan12,Adam10,Tspan12,0.263227,0.232543,0.080002,0.075099,0.004895,0.010,0.126238,...,resource_specific,O95859,TSPAN12,protein,2.0,False,True,False,True,False
2,Adam10^Axl,Adam10,Axl,0.263227,0.232543,0.139795,0.129776,0.008592,0.001,0.188329,...,resource_specific,P30530,AXL,protein,22.0,False,True,False,True,False
3,Adam10^Notch1,Adam10,Notch1,0.263227,0.232543,0.059135,0.053360,0.006972,0.000,0.112873,...,resource_specific,P46531,NOTCH1,protein,22.0,False,True,False,True,False
4,Adam10^Nrcam,Adam10,Nrcam,0.263227,0.232543,0.581581,0.448617,0.011237,0.000,0.329755,...,resource_specific,Q92823,NRCAM,protein,9.0,False,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404,Mfge8^Itgb5,Mfge8,Itgb5,1.321267,0.743412,0.184464,0.157444,0.012862,0.000,0.339269,...,resource_specific,P18084,ITGB5,protein,14.0,False,True,False,True,False
405,Ado^Adora2a,Ado,Adora2a,0.209847,0.176219,0.391031,0.271080,-0.007746,1.000,0.176476,...,resource_specific,P29274,ADORA2A,protein,10.0,False,True,False,True,False
406,Gdf11^Actr2,Gdf11,Actr2,0.069398,0.063241,0.411244,0.342885,0.003341,0.050,0.131526,...,NaN,None,None,NaN,NaN,None,None,None,None,None
407,Inhba^Actr2,Inhba,Actr2,0.075964,0.070817,0.411244,0.342885,0.001460,0.240,0.151698,...,NaN,None,None,NaN,NaN,None,None,None,None,None
408,C4b^Nrp1,C4b,Nrp1,0.102228,0.083004,0.157399,0.135705,-0.000340,0.566,0.083262,...,NaN,None,None,NaN,NaN,None,None,None,None,None